# Imports

In [18]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Loading Data

In [2]:
fifteen = pd.read_csv("2015.csv")
sixteen = pd.read_csv("2016.csv")
seventeen = pd.read_csv("2017.csv")
eighteen = pd.read_csv("2018.csv")
nineteen = pd.read_csv("2019.csv")
twenty = pd.read_csv("2020.csv")
twentyone = pd.read_csv("2021.csv")
twentytwo = pd.read_csv("2022.csv")

In [3]:
fifteen.columns

Index(['Country', 'Region', 'Happiness Rank', 'Happiness Score',
       'Standard Error', 'Economy (GDP per Capita)', 'Family',
       'Health (Life Expectancy)', 'Freedom', 'Trust (Government Corruption)',
       'Generosity', 'Dystopia Residual'],
      dtype='object')

In [4]:
sixteen.columns

Index(['Country', 'Region', 'Happiness Rank', 'Happiness Score',
       'Lower Confidence Interval', 'Upper Confidence Interval',
       'Economy (GDP per Capita)', 'Family', 'Health (Life Expectancy)',
       'Freedom', 'Trust (Government Corruption)', 'Generosity',
       'Dystopia Residual'],
      dtype='object')

In [5]:
seventeen.columns

Index(['Country', 'Happiness.Rank', 'Happiness.Score', 'Whisker.high',
       'Whisker.low', 'Economy..GDP.per.Capita.', 'Family',
       'Health..Life.Expectancy.', 'Freedom', 'Generosity',
       'Trust..Government.Corruption.', 'Dystopia.Residual'],
      dtype='object')

The relevant columns are:
1. Country
2. Happyness Rank
3. Happyness Score
4. Economy
5. Family
6. Health
7. Freedom
8. Generosity
9. Corruption
10. Region
11. Dystopia Residual

Some of the dataframes does not have some of these columns and some have more than these columns. We'll need to clean the data to make sure that columns are consistent.

# Preporcessing

## Standardizing the Data

### Fifteen

In [6]:
fifteen.columns

Index(['Country', 'Region', 'Happiness Rank', 'Happiness Score',
       'Standard Error', 'Economy (GDP per Capita)', 'Family',
       'Health (Life Expectancy)', 'Freedom', 'Trust (Government Corruption)',
       'Generosity', 'Dystopia Residual'],
      dtype='object')

Let's drop the extra column.

In [7]:
fifteen.drop(columns=["Standard Error"], axis=1, inplace=True)

Now, the columns of this dataset will be the standard columns.

In [8]:
standard_columns = fifteen.columns.tolist()

### Sixteen

In [9]:
sixteen.columns

Index(['Country', 'Region', 'Happiness Rank', 'Happiness Score',
       'Lower Confidence Interval', 'Upper Confidence Interval',
       'Economy (GDP per Capita)', 'Family', 'Health (Life Expectancy)',
       'Freedom', 'Trust (Government Corruption)', 'Generosity',
       'Dystopia Residual'],
      dtype='object')

We'll again drop the extra columns

In [10]:
sixteen.drop(columns=['Lower Confidence Interval', 'Upper Confidence Interval'], axis=1, inplace=True)

In [11]:
def compare_columns(columns):
    for column in columns:
        if column not in standard_columns:
            return False
    return True

In [12]:
compare_columns(sixteen.columns)

True

Great! Next dataset.

### Seventeen

In [13]:
seventeen.columns

Index(['Country', 'Happiness.Rank', 'Happiness.Score', 'Whisker.high',
       'Whisker.low', 'Economy..GDP.per.Capita.', 'Family',
       'Health..Life.Expectancy.', 'Freedom', 'Generosity',
       'Trust..Government.Corruption.', 'Dystopia.Residual'],
      dtype='object')

We have to drop some columns and rename the others. Also, we'll need to add the Region column.

In [14]:
seventeen.drop(columns=['Whisker.high', 'Whisker.low'], axis=1, inplace=True)

In [15]:
standard_columns

['Country',
 'Region',
 'Happiness Rank',
 'Happiness Score',
 'Economy (GDP per Capita)',
 'Family',
 'Health (Life Expectancy)',
 'Freedom',
 'Trust (Government Corruption)',
 'Generosity',
 'Dystopia Residual']

In [16]:
seventeen.columns = ['Country',
#  'Region',
 'Happiness Rank',
 'Happiness Score',
 'Economy (GDP per Capita)',
 'Family',
 'Health (Life Expectancy)',
 'Freedom',
 'Generosity',
 'Trust (Government Corruption)',
 'Dystopia Residual']

Now the Region column.

In [17]:
seventeen.head()

,Country,Happiness Rank,Happiness Score,Economy (GDP per Capita),Family,Health (Life Expectancy),Freedom,Generosity,Trust (Government Corruption),Dystopia Residual
0,Norway,1,7.537,1.616463,1.533524,0.796667,0.635423,0.362012,0.315964,2.277027
1,Denmark,2,7.522,1.482383,1.551122,0.792566,0.626007,0.355280,0.400770,2.313707
2,Iceland,3,7.504,1.480633,1.610574,0.833552,0.627163,0.475540,0.153527,2.322715
3,Switzerland,4,7.494,1.564980,1.516912,0.858131,0.620071,0.290549,0.367007,2.276716
4,Finland,5,7.469,1.443572,1.540247,0.809158,0.617951,0.245483,0.382612,2.430182

In [18]:
seventeen = pd.merge(seventeen, sixteen[["Region", "Country"]], on='Country')
seventeen.head()

,Country,Happiness Rank,Happiness Score,Economy (GDP per Capita),Family,Health (Life Expectancy),Freedom,Generosity,Trust (Government Corruption),Dystopia Residual,Region
0,Norway,1,7.537,1.616463,1.533524,0.796667,0.635423,0.362012,0.315964,2.277027,Western Europe
1,Denmark,2,7.522,1.482383,1.551122,0.792566,0.626007,0.355280,0.400770,2.313707,Western Europe
2,Iceland,3,7.504,1.480633,1.610574,0.833552,0.627163,0.475540,0.153527,2.322715,Western Europe
3,Switzerland,4,7.494,1.564980,1.516912,0.858131,0.620071,0.290549,0.367007,2.276716,Western Europe
4,Finland,5,7.469,1.443572,1.540247,0.809158,0.617951,0.245483,0.382612,2.430182,Western Europe

### Eighteen

In [19]:
eighteen.columns

Index(['Overall rank', 'Country or region', 'Score', 'GDP per capita',
       'Social support', 'Healthy life expectancy',
       'Freedom to make life choices', 'Generosity',
       'Perceptions of corruption'],
      dtype='object')

Okay, it seems the 2018 dataset does not contain the column 'Dystopia Residual'.

In [20]:
cols = ['Happiness Rank',
 'Country',
#  'Region',
 'Happiness Score',
 'Economy (GDP per Capita)',
 'Family',
 'Health (Life Expectancy)',
 'Freedom',
 'Generosity',
 'Trust (Government Corruption)',
#  'Dystopia Residual'
 ]

eighteen.columns = cols

Let's add the Region column.

In [21]:
standard_columns

['Country',
 'Region',
 'Happiness Rank',
 'Happiness Score',
 'Economy (GDP per Capita)',
 'Family',
 'Health (Life Expectancy)',
 'Freedom',
 'Trust (Government Corruption)',
 'Generosity',
 'Dystopia Residual']

In [22]:
eighteen = pd.merge(eighteen, sixteen[["Region", "Country"]], on='Country')
eighteen.head()

,Happiness Rank,Country,Happiness Score,Economy (GDP per Capita),Family,Health (Life Expectancy),Freedom,Generosity,Trust (Government Corruption),Region
0,1,Finland,7.632,1.305,1.592,0.874,0.681,0.202,0.393,Western Europe
1,2,Norway,7.594,1.456,1.582,0.861,0.686,0.286,0.340,Western Europe
2,3,Denmark,7.555,1.351,1.590,0.868,0.683,0.284,0.408,Western Europe
3,4,Iceland,7.495,1.343,1.644,0.914,0.677,0.353,0.138,Western Europe
4,5,Switzerland,7.487,1.420,1.549,0.927,0.660,0.256,0.357,Western Europe

### Nineteen

In [23]:
nineteen.columns

Index(['Overall rank', 'Country or region', 'Score', 'GDP per capita',
       'Social support', 'Healthy life expectancy',
       'Freedom to make life choices', 'Generosity',
       'Perceptions of corruption'],
      dtype='object')

This dataset, too, does not have the column 'Dystopia Residual'.

In [24]:
cols = ['Happiness Rank',
 'Country',
#  'Region',
 'Happiness Score',
 'Economy (GDP per Capita)',
 'Family',
 'Health (Life Expectancy)',
 'Freedom',
 'Generosity',
 'Trust (Government Corruption)',
#  'Dystopia Residual'
 ]
nineteen.columns = cols

Let's add the Region column.

In [25]:
nineteen = pd.merge(nineteen, sixteen[["Region", "Country"]], on='Country')
nineteen.head()

,Happiness Rank,Country,Happiness Score,Economy (GDP per Capita),Family,Health (Life Expectancy),Freedom,Generosity,Trust (Government Corruption),Region
0,1,Finland,7.769,1.340,1.587,0.986,0.596,0.153,0.393,Western Europe
1,2,Denmark,7.600,1.383,1.573,0.996,0.592,0.252,0.410,Western Europe
2,3,Norway,7.554,1.488,1.582,1.028,0.603,0.271,0.341,Western Europe
3,4,Iceland,7.494,1.380,1.624,1.026,0.591,0.354,0.118,Western Europe
4,5,Netherlands,7.488,1.396,1.522,0.999,0.557,0.322,0.298,Western Europe

### Twenty

In [26]:
twenty.columns

Index(['Country name', 'Regional indicator', 'Ladder score',
       'Standard error of ladder score', 'upperwhisker', 'lowerwhisker',
       'Logged GDP per capita', 'Social support', 'Healthy life expectancy',
       'Freedom to make life choices', 'Generosity',
       'Perceptions of corruption', 'Ladder score in Dystopia',
       'Explained by: Log GDP per capita', 'Explained by: Social support',
       'Explained by: Healthy life expectancy',
       'Explained by: Freedom to make life choices',
       'Explained by: Generosity', 'Explained by: Perceptions of corruption',
       'Dystopia + residual'],
      dtype='object')

We need to drop the extra columns.

In [27]:
twenty.drop(columns=[
       'Standard error of ladder score', 'upperwhisker', 'lowerwhisker',
       'Ladder score in Dystopia',
       'Explained by: Log GDP per capita', 'Explained by: Social support',
       'Explained by: Healthy life expectancy',
       'Explained by: Freedom to make life choices',
       'Explained by: Generosity', 'Explained by: Perceptions of corruption',
       ], axis=1, inplace=True)
twenty.columns

Index(['Country name', 'Regional indicator', 'Ladder score',
       'Logged GDP per capita', 'Social support', 'Healthy life expectancy',
       'Freedom to make life choices', 'Generosity',
       'Perceptions of corruption', 'Dystopia + residual'],
      dtype='object')

In [28]:
standard_columns

['Country',
 'Region',
 'Happiness Rank',
 'Happiness Score',
 'Economy (GDP per Capita)',
 'Family',
 'Health (Life Expectancy)',
 'Freedom',
 'Trust (Government Corruption)',
 'Generosity',
 'Dystopia Residual']

We need to create the happiness rank. Let's do this next.

In [29]:
twenty = twenty.sort_values('Ladder score', ascending=False).reset_index()

In [30]:
twenty['Happiness Rank'] = twenty['index'] +1
twenty.head()

,index,Country name,Regional indicator,Ladder score,Logged GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,Generosity,Perceptions of corruption,Dystopia + residual,Happiness Rank
0,0,Finland,Western Europe,7.8087,10.639267,0.954330,71.900825,0.949172,-0.059482,0.195445,2.762835,1
1,1,Denmark,Western Europe,7.6456,10.774001,0.955991,72.402504,0.951444,0.066202,0.168489,2.432741,2
2,2,Switzerland,Western Europe,7.5599,10.979933,0.942847,74.102448,0.921337,0.105911,0.303728,2.350267,3
3,3,Iceland,Western Europe,7.5045,10.772559,0.974670,73.000000,0.948892,0.246944,0.711710,2.460688,4
4,4,Norway,Western Europe,7.4880,11.087804,0.952487,73.200783,0.955750,0.134533,0.263218,2.168266,5

In [31]:
twenty.drop(columns=['index'], axis=1, inplace=True)

In [32]:
twenty.columns

Index(['Country name', 'Regional indicator', 'Ladder score',
       'Logged GDP per capita', 'Social support', 'Healthy life expectancy',
       'Freedom to make life choices', 'Generosity',
       'Perceptions of corruption', 'Dystopia + residual', 'Happiness Rank'],
      dtype='object')

In [33]:
cols = [ 'Country',
 'Region',
  'Happiness Score',
 'Economy (GDP per Capita)',
 'Family',
 'Health (Life Expectancy)',
 'Freedom',
 'Generosity',
 'Trust (Government Corruption)',
 'Dystopia Residual',
 'Happiness Rank',
 ]
twenty.columns = cols

### Twenty-one

In [34]:
twentyone.columns

Index(['Country name', 'Regional indicator', 'Ladder score',
       'Standard error of ladder score', 'upperwhisker', 'lowerwhisker',
       'Logged GDP per capita', 'Social support', 'Healthy life expectancy',
       'Freedom to make life choices', 'Generosity',
       'Perceptions of corruption', 'Ladder score in Dystopia',
       'Explained by: Log GDP per capita', 'Explained by: Social support',
       'Explained by: Healthy life expectancy',
       'Explained by: Freedom to make life choices',
       'Explained by: Generosity', 'Explained by: Perceptions of corruption',
       'Dystopia + residual'],
      dtype='object')

This is similar to the previous datasetr. We should just repeat the process.

In [35]:
twentyone.drop(columns=[
       'Standard error of ladder score', 'upperwhisker', 'lowerwhisker',
       'Ladder score in Dystopia',
       'Explained by: Log GDP per capita', 'Explained by: Social support',
       'Explained by: Healthy life expectancy',
       'Explained by: Freedom to make life choices',
       'Explained by: Generosity', 'Explained by: Perceptions of corruption',
       ], axis=1, inplace=True)
twentyone.columns
twentyone = twentyone.sort_values('Ladder score', ascending=False).reset_index()

twentyone['Happiness Rank'] = twentyone['index'] +1
twentyone.drop(columns=['index'], axis=1, inplace=True)

In [36]:
cols = [ 'Country',
 'Region',
  'Happiness Score',
 'Economy (GDP per Capita)',
 'Family',
 'Health (Life Expectancy)',
 'Freedom',
 'Generosity',
 'Trust (Government Corruption)',
 'Dystopia Residual',
 'Happiness Rank',
 ]
twentyone.columns = cols

### Twenty-two

In [37]:
twentytwo.columns

Index(['RANK', 'Country', 'Happiness score', 'Whisker-high', 'Whisker-low',
       'Dystopia (1.83) + residual', 'Explained by: GDP per capita',
       'Explained by: Social support', 'Explained by: Healthy life expectancy',
       'Explained by: Freedom to make life choices',
       'Explained by: Generosity', 'Explained by: Perceptions of corruption'],
      dtype='object')

Okay, this dataset does not contain a lot of the standard columns. We'll drop the extra columns anyway.

In [39]:
twentytwo.drop(columns=['Whisker-high', 'Whisker-low','Explained by: GDP per capita',
       'Explained by: Social support', 'Explained by: Healthy life expectancy',
       'Explained by: Freedom to make life choices',
       'Explained by: Generosity', 'Explained by: Perceptions of corruption'], axis=1, inplace=True)

Let's rename the columns.

In [41]:
standard_columns

['Country',
 'Region',
 'Happiness Rank',
 'Happiness Score',
 'Economy (GDP per Capita)',
 'Family',
 'Health (Life Expectancy)',
 'Freedom',
 'Trust (Government Corruption)',
 'Generosity',
 'Dystopia Residual']

In [42]:
twentytwo.columns =[
    'Happiness Rank',
    'Country',
    'Happiness Score',
    'Dystopia Residual'
]

## Null Values

Let's see if the datasets contain null values.

In [44]:
dfs = [fifteen, sixteen, seventeen, eighteen, nineteen, twenty, twentyone, twentytwo]
for df in dfs:
    display(df.isna().sum())

Country                          0
Region                           0
Happiness Rank                   0
Happiness Score                  0
Economy (GDP per Capita)         0
Family                           0
Health (Life Expectancy)         0
Freedom                          0
Trust (Government Corruption)    0
Generosity                       0
Dystopia Residual                0
dtype: int64

Country                          0
Region                           0
Happiness Rank                   0
Happiness Score                  0
Economy (GDP per Capita)         0
Family                           0
Health (Life Expectancy)         0
Freedom                          0
Trust (Government Corruption)    0
Generosity                       0
Dystopia Residual                0
dtype: int64

Country                          0
Happiness Rank                   0
Happiness Score                  0
Economy (GDP per Capita)         0
Family                           0
Health (Life Expectancy)         0
Freedom                          0
Generosity                       0
Trust (Government Corruption)    0
Dystopia Residual                0
Region                           0
dtype: int64

Happiness Rank                   0
Country                          0
Happiness Score                  0
Economy (GDP per Capita)         0
Family                           0
Health (Life Expectancy)         0
Freedom                          0
Generosity                       0
Trust (Government Corruption)    1
Region                           0
dtype: int64

Happiness Rank                   0
Country                          0
Happiness Score                  0
Economy (GDP per Capita)         0
Family                           0
Health (Life Expectancy)         0
Freedom                          0
Generosity                       0
Trust (Government Corruption)    0
Region                           0
dtype: int64

Country                          0
Region                           0
Happiness Score                  0
Economy (GDP per Capita)         0
Family                           0
Health (Life Expectancy)         0
Freedom                          0
Generosity                       0
Trust (Government Corruption)    0
Dystopia Residual                0
Happiness Rank                   0
dtype: int64

Country                          0
Region                           0
Happiness Score                  0
Economy (GDP per Capita)         0
Family                           0
Health (Life Expectancy)         0
Freedom                          0
Generosity                       0
Trust (Government Corruption)    0
Dystopia Residual                0
Happiness Rank                   0
dtype: int64

Happiness Rank       0
Country              0
Happiness Score      1
Dystopia Residual    1
dtype: int64

The dataset twentytwo has one null value. Let's see it.

In [46]:
twentytwo[twentytwo["Happiness Score"].isna()]

     Happiness Rank Country  Happiness Score  Dystopia Residual
146             147      xx              NaN                NaN

It seems that this entry does not seems to be a valid entry. Let's drop it.

In [47]:
twentytwo.dropna(subset=['Happiness Score'], inplace=True)

## Creating a Single Dataset

In [48]:
for df in dfs:
    print(df.shape)

(158, 11)
(157, 11)
(150, 11)
(151, 10)
(148, 10)
(153, 11)
(149, 11)
(146, 4)

Let's save the datasets.

In [49]:
fifteen.to_csv("2015_final.csv", index=False)
sixteen.to_csv("2016_final.csv", index=False)
seventeen.to_csv("2017_final.csv", index=False)
eighteen.to_csv("2018_final.csv", index=False)
nineteen.to_csv("2019_final.csv", index=False)
twenty.to_csv("2020_final.csv", index=False)
twentyone.to_csv("2021_final.csv", index=False)
twentytwo.to_csv("2022_final.csv", index=False)

Next, we'll merge all these datasets into one.

In [3]:
fifteen= pd.read_csv("2015_final.csv")
sixteen= pd.read_csv("2016_final.csv")
seventeen= pd.read_csv("2017_final.csv")
eighteen= pd.read_csv("2018_final.csv")
nineteen= pd.read_csv("2019_final.csv")
twenty= pd.read_csv("2020_final.csv")
twentyone= pd.read_csv("2021_final.csv")
twentytwo= pd.read_csv("2022_final.csv")

In [13]:
df_temp = pd.merge(fifteen, sixteen, on='Country', suffixes=['_2015', '_2016'])
df_temp_2 = pd.merge(seventeen, eighteen, on='Country', suffixes=['_2017', '_2018'])
df_temp_3 = pd.merge(nineteen, twenty, on='Country', suffixes=['_2019', '_2020'])
df_temp_4 = pd.merge(twentyone, twentytwo, on='Country', suffixes=['_2021', '_2022'])

In [15]:
df_temp_5 = pd.merge(df_temp, df_temp_2, on='Country')
df_temp_6 = pd.merge(df_temp_5, df_temp_3, on='Country')
df_temp_7 = pd.merge(df_temp_6, df_temp_4, on='Country')
df_temp_7.columns

Index(['Country', 'Region_2015', 'Happiness Rank_2015', 'Happiness Score_2015',
       'Economy (GDP per Capita)_2015', 'Family_2015',
       'Health (Life Expectancy)_2015', 'Freedom_2015',
       'Trust (Government Corruption)_2015', 'Generosity_2015',
       'Dystopia Residual_2015', 'Region_2016', 'Happiness Rank_2016',
       'Happiness Score_2016', 'Economy (GDP per Capita)_2016', 'Family_2016',
       'Health (Life Expectancy)_2016', 'Freedom_2016',
       'Trust (Government Corruption)_2016', 'Generosity_2016',
       'Dystopia Residual_2016', 'Happiness Rank_2017', 'Happiness Score_2017',
       'Economy (GDP per Capita)_2017', 'Family_2017',
       'Health (Life Expectancy)_2017', 'Freedom_2017', 'Generosity_2017',
       'Trust (Government Corruption)_2017', 'Dystopia Residual_x',
       'Region_2017', 'Happiness Rank_2018', 'Happiness Score_2018',
       'Economy (GDP per Capita)_2018', 'Family_2018',
       'Health (Life Expectancy)_2018', 'Freedom_2018', 'Generosity_2018',
       'Trust (Government Corruption)_2018', 'Region_2018',
       'Happiness Rank_2019', 'Happiness Score_2019',
       'Economy (GDP per Capita)_2019', 'Family_2019',
       'Health (Life Expectancy)_2019', 'Freedom_2019', 'Generosity_2019',
       'Trust (Government Corruption)_2019', 'Region_2019', 'Region_2020',
       'Happiness Score_2020', 'Economy (GDP per Capita)_2020', 'Family_2020',
       'Health (Life Expectancy)_2020', 'Freedom_2020', 'Generosity_2020',
       'Trust (Government Corruption)_2020', 'Dystopia Residual_y',
       'Happiness Rank_2020', 'Region', 'Happiness Score_2021',
       'Economy (GDP per Capita)', 'Family', 'Health (Life Expectancy)',
       'Freedom', 'Generosity', 'Trust (Government Corruption)',
       'Dystopia Residual_2021', 'Happiness Rank_2021', 'Happiness Rank_2022',
       'Happiness Score_2022', 'Dystopia Residual_2022'],
      dtype='object')

In [16]:
df_temp_7.isna().sum()

Country                          0
Region_2015                      0
Happiness Rank_2015              0
Happiness Score_2015             0
Economy (GDP per Capita)_2015    0
                                ..
Dystopia Residual_2021           0
Happiness Rank_2021              0
Happiness Rank_2022              0
Happiness Score_2022             0
Dystopia Residual_2022           0
Length: 72, dtype: int64

In [17]:
df_temp_7.to_csv("Final_Happiness_Score.csv", index=False)

In [19]:
df = pd.read_csv("Final_Happiness_Score.csv")

We are going to make some geo graphs. We need the country code for that. Let's get the country code.

In [20]:
gdp_df = pd.read_csv("GlobalGDP.txt")

In [27]:
gdp_df.columns = ['Country', 'GDP', "Code"]

In [29]:
gdp_df.shape

(222, 3)

In [30]:
df.shape

(117, 72)

In [31]:
df = pd.merge(df, gdp_df[["Country", "Code"]], on='Country')

In [32]:
df.to_csv("Happiness_Score_with_Country_Code.csv", index=False)